# fly.toml app configuration file generated for ancient-hill-8637 on 2023-09-05T19:40:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ancient-hill-8637"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 100000
    tls_skip_verify = false



